### PR TITLE
[ENH] Add API response examples and code to generate them

### LINKED ISSUE #31: Create examples of all API responses
It would make using and testing the APIs a big deal easier to have up to date examples of

- successful response
- partial failed response
- failed response

for all of the API routes for the f-API, and expect that 2/3 nodes is protected, and 1/3 nodes are not protected.

We should also provide examples of protected & non-protected responses for n-API repositories. 

This is similar to the examples of query tool results in https://github.com/neurobagel/neurobagel_examples.
So we should find a way to provide these and keep them current. Ideally via an automatic process that updates the examples every time the APIs change.

- [x] make the examples by hand (with script), not recurring
- [x] provide a script that makes the examples

### PR DESCRIPTION
**Pull request by alyssadai**
- Closes #31 

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

### CODE REVIEW

File: api-responses/make_api_responses.sh [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+
+mkdir test_node1 test_node2 api-responses
+
+# SETUP FOR TEST NODE 1
+git clone https://github.com/neurobagel/recipes.git test_node1/recipes
+
+# Get the data
+git clone https://github.com/neurobagel/openneuro-annotations.git test_node1/openneuro-annotations
+mkdir test_node1/openneuro_mini_data
+cp test_node1/openneuro-annotations/ds000001.jsonld test_node1/recipes/ds000001.jsonld test_node1/openneuro_mini_data
```
Comment (surchs) [inline api-responses/make_api_responses.sh:15]: Is that intentionally the same dataset twice?

File: api-responses/make_api_responses.sh [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+cd test_node1/recipes
+cp template.env .env
+
+sed -i 's/^LOCAL_GRAPH_DATA=.*/LOCAL_GRAPH_DATA=../openneuro_mini_data/' .env
+sed -i 's/^NB_FEDERATE_REMOTE_PUBLIC_NODES=.*/NB_FEDERATE_REMOTE_PUBLIC_NODES=False/' .env
+sed -i 's/^NB_API_QUERY_URL=.*/NB_API_QUERY_URL=http://localhost:8080/' .env
+sed -i 's/^COMPOSE_PROFILES=.*/COMPOSE_PROFILES=full_stack/' .env
+
+# Use full container names to avoid conflicts
+echo '[{"NodeName": "2 OpenNeuro Datasets", "ApiURL": "http://neurobagel_node-api-1:8000"},{"NodeName": "BIDS Synthetic", "ApiURL": "http://neurobagel_node2-api-1:8000"}]' > local_nb_nodes.json
```
Comment (surchs) [inline api-responses/make_api_responses.sh:26]: Interesting, did you experience an error when using the service name? Or is this needed because the nodes are not on the same docker network?

**Review by surchs — APPROVED** [review]

File: api-responses/make_api_responses.sh (hunk 1 above)
Comment (alyssadai) [reply api-responses/make_api_responses.sh]: Ah, that was a typo - thanks for catching that

File: api-responses/make_api_responses.sh (hunk 2 above)
Comment (alyssadai) [reply api-responses/make_api_responses.sh:26]: You mean just `api` alone? The issue is that in each node's recipe, the n-API always has the same Compose _service_, name `api`, so we need a way to deconflict the two n-APIs / make sure we know which `api` we're referring to once they're in the same network. To do that explicitly, here we're using the _container_ names that the n-APIs will have once running, which by default will have the Docker Compose project name prepended to it (and at this point we've manually changed the project name for one of the two nodes).

The n-APIs need to be in the same Docker network as the f-API for the f-API to be able to refer to them by either service name or container name. That's why we have this line in the script as well:

```
docker network add neurobagel_node_default neurobagel_node2-api-1
```
